# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: update_engine.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='update_engine.proto',
  package='update_engine',
  syntax='proto3',
  serialized_options=_b('H\003'),
  serialized_pb=_b('\n\x13update_engine.proto\x12\rupdate_engine\"\xdd\x01\n\x0cStatusResult\x12\x19\n\x11last_checked_time\x18\x01 \x01(\x03\x12\x10\n\x08progress\x18\x02 \x01(\x01\x12\x33\n\x11\x63urrent_operation\x18\x03 \x01(\x0e\x32\x18.update_engine.Operation\x12\x13\n\x0bnew_version\x18\x04 \x01(\t\x12\x10\n\x08new_size\x18\x05 \x01(\x03\x12\x1e\n\x16is_enterprise_rollback\x18\x06 \x01(\x08\x12\x12\n\nis_install\x18\x07 \x01(\x08\x12\x10\n\x08\x65ol_date\x18\x08 \x01(\x03*\x82\x02\n\tOperation\x12\x08\n\x04IDLE\x10\x00\x12\x17\n\x13\x43HECKING_FOR_UPDATE\x10\x01\x12\x14\n\x10UPDATE_AVAILABLE\x10\x02\x12\x0f\n\x0b\x44OWNLOADING\x10\x03\x12\r\n\tVERIFYING\x10\x04\x12\x0e\n\nFINALIZING\x10\x05\x12\x17\n\x13UPDATED_NEED_REBOOT\x10\x06\x12\x19\n\x15REPORTING_ERROR_EVENT\x10\x07\x12\x17\n\x13\x41TTEMPTING_ROLLBACK\x10\x08\x12\x0c\n\x08\x44ISABLED\x10\t\x12\x1d\n\x19NEED_PERMISSION_TO_UPDATE\x10\n\x12\x12\n\x05\x45RROR\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01\x42\x02H\x03\x62\x06proto3')
)

_OPERATION = _descriptor.EnumDescriptor(
  name='Operation',
  full_name='update_engine.Operation',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='IDLE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CHECKING_FOR_UPDATE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UPDATE_AVAILABLE', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DOWNLOADING', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VERIFYING', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FINALIZING', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UPDATED_NEED_REBOOT', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REPORTING_ERROR_EVENT', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ATTEMPTING_ROLLBACK', index=8, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DISABLED', index=9, number=9,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NEED_PERMISSION_TO_UPDATE', index=10, number=10,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=11, number=-1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=263,
  serialized_end=521,
)
_sym_db.RegisterEnumDescriptor(_OPERATION)

Operation = enum_type_wrapper.EnumTypeWrapper(_OPERATION)
IDLE = 0
CHECKING_FOR_UPDATE = 1
UPDATE_AVAILABLE = 2
DOWNLOADING = 3
VERIFYING = 4
FINALIZING = 5
UPDATED_NEED_REBOOT = 6
REPORTING_ERROR_EVENT = 7
ATTEMPTING_ROLLBACK = 8
DISABLED = 9
NEED_PERMISSION_TO_UPDATE = 10
ERROR = -1



_STATUSRESULT = _descriptor.Descriptor(
  name='StatusResult',
  full_name='update_engine.StatusResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='last_checked_time', full_name='update_engine.StatusResult.last_checked_time', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='progress', full_name='update_engine.StatusResult.progress', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='current_operation', full_name='update_engine.StatusResult.current_operation', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='new_version', full_name='update_engine.StatusResult.new_version', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='new_size', full_name='update_engine.StatusResult.new_size', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_enterprise_rollback', full_name='update_engine.StatusResult.is_enterprise_rollback', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_install', full_name='update_engine.StatusResult.is_install', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='eol_date', full_name='update_engine.StatusResult.eol_date', index=7,
      number=8, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=260,
)

_STATUSRESULT.fields_by_name['current_operation'].enum_type = _OPERATION
DESCRIPTOR.message_types_by_name['StatusResult'] = _STATUSRESULT
DESCRIPTOR.enum_types_by_name['Operation'] = _OPERATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StatusResult = _reflection.GeneratedProtocolMessageType('StatusResult', (_message.Message,), {
  'DESCRIPTOR' : _STATUSRESULT,
  '__module__' : 'update_engine_pb2'
  # @@protoc_insertion_point(class_scope:update_engine.StatusResult)
  })
_sym_db.RegisterMessage(StatusResult)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
